[build]
  command = CI='' npm run build
  commandOrigin: config
  environment: [CI=true]
  publish: /opt/build/repo/build
  publishOrigin: ui

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200